# Generated by Django 4.0.4 on 2022-08-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0002_category_glass_ingredient_drink_user_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='glass',
            options={'verbose_name_plural': 'glasses'},
        ),
        migrations.AlterField(
            model_name='drink',
            name='glass',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='used_for', to='shaker.glass'),
        ),
    ]
