# Generated by Django 4.0.4 on 2022-08-16 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0005_alter_drink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
