# Generated by Django 4.0.4 on 2022-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0007_alter_drink_glass_alter_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='used_for', to='shaker.ingredient'),
        ),
    ]
